### ISSUE TITLE
Links exiting disqus posts handled incorrectly

### ISSUE THREAD

**Issue by kerframil** [sblask/firefox-skip-redirect#18]
This ...

```
https://disq.us/url?url=https%3A%2F%2Fgithub.com%2Fchocolatey%2Fchocolatey-coreteampackages%2Fissues%3Futf8%3D%25E2%259C%2593%26q%3Dis%253Aissue%2Bis%253Aopen%2Bcygwin%3AzR1nhyZLRtg8Y_rhtqSlAOeHI7Q&cuid=2163236
```

... is cleaned up as:

```
https://github.com/chocolatey/chocolatey-coreteampackages/issues?utf8=%E2%9C%93&q=is:issue+is:open+cygwin:zR1nhyZLRtg8Y_rhtqSlAOeHI7Q
```

In this case, it incorrectly incorporates `:zR1nhyZLRtg8Y_rhtqSlAOeHI7Q`, thus breaking the search terms that are conveyed. By the looks of it, the portion that can be omitted will always match `:\w{27}&cuid=\d+$` after decoding.

**Comment by sblask** [comment]
I can see how this is frustrating, but this add-on is not rule based - it tries to extract URLs generically without knowledge of where the URL comes from. So in this case we've got a query parameter named `url` with a value of `https%3A%2F%2Fgithub.com%2Fchocolatey%2Fchocolatey-coreteampackages%2Fissues%3Futf8%3D%25E2%259C%2593%26q%3Dis%253Aissue%2Bis%253Aopen%2Bcygwin%3AzR1nhyZLRtg8Y_rhtqSlAOeHI7Q` There is no way of knowing whether there is anything that doesn't belong in here and actually the way they are doing it is strange. Why do they not use another query parameter for whatever they use `zR1nhyZLRtg8Y_rhtqSlAOeHI7Q` for? And I don't even know who "they" is, is it disqus or github doing weird stuff? it seems to be disqus though because github would filter it away?

**Comment by kerframil** [comment]
Yes, it's done by disqus. Peruse any embedded disqus forum where someone has included a link in the post body and you'll see that the pattern seems to always be the same. That is, the resulting disqus post will contain a link whose target has been altered in two ways:

1) it is prefixed with `http://disq.us/url?url=` (or https, where appropriate)
2) it is affixed with a colon, followed by 27 characters that can be alphanumeric/underscores, followed by `&cuid=`, followed by one or more digits

When your add-on is enabled, the portion described by (2) survives, but it shouldn't. I agree that it's unfortunate that disqus didn't elect to make use of an additional parameter but this is the way it is.

While this is not the fault of Github, I provided this particular sample because I discovered the issue after following that exact link, having installed your add-on. Indeed, Github does not strip all of the text referred to by (2). For all they know, the text between the "q" parameter and the "cuid" parameter constitutes the search terms in their entirety so why would they? This is actually one of the more benign cases because a majority of links that exit from disqus posts will result in a 404 instead.

It's trivial to capture the correct URL (if you'll excuse the Perl as my Javascript is rusty). However, as the issue pertains to disqus URLs, the use of a non-generic pattern is implied ...

```perl
$url = 'https://disq.us/url?url=https%3A%2F%2Fgithub.com%2Fchocolatey%2Fchocolatey-coreteampackages%2Fissues%3Futf8%3D%25E2%259C%2593%26q%3Dis%253Aissue%2Bis%253Aopen%2Bcygwin%3AzR1nhyZLRtg8Y_rhtqSlAOeHI7Q&cuid=2163236';

if ($url =~ /^https?:\/\/disq\.us\/url\?url=(.+?)%3A[[:alnum:]_]{27}&cuid=\d+$/) {
        $clean_url = $1;
}

# Prints: https%3A%2F%2Fgithub.com%2Fchocolatey%2Fchocolatey-coreteampackages%2Fissues%3Futf8%3D%25E2%259C%2593%26q%3Dis%253Aissue%2Bis%253Aopen%2Bcygwin
print "$clean_url\n";
```

If you don't want to make disqus a special case then it would seem that the issue cannot be resolved. However, doing so would increase the value of your add-on, given that disqus enjoys widespread usage.

**Comment by sblask** [comment]
The approach this add-on is using is flawed and there are many sites where it causes problems, that's why you can add exceptions in the preferences. I won't maintain site specific exceptions. I might at some point add a mode where skipping has to be enabled for sites explicitly, but that's about it...

**Comment by kerframil** [comment]
Alright. I'll close the issue then.
