### ISSUE TITLE
adding pages

### ISSUE THREAD

**Issue by zohar101** [sblask/firefox-skip-redirect#5]
You mention reporting pages on which redirect is failing but is there a way to simply have a button of some sort within the addon to press every time redirect fails so we don't have to write a github ticket to report it? Or a simpler way to add failures somewhere? An editable list of some sort perhaps?

**Comment by sblask** [comment]
I did not get any valid failure reports yet and I guess even if, I would need some more explanation and the possibility to ask questions/give feedback. So a quick report button doesn't make sense to me. And if people have to describe what the problem is and give an email address, they can write an email in the first place? The support mail address can be found on the addon page...
